<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9Z6mDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9Z6mDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW9Z6mDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW9Z6mDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW9Z6mDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'W9Z6mDx',
    'container.build_id' => 'b18eeb77',
    'container.build_time' => 1589250528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9Z6mDx');
